export { default as Home } from './Home';
export { default as Auth } from './Auth';
export { default as Write } from './Write';
export { default as Post } from './Post';
export { default as Tag } from './Tag';
export { default as User } from './User';
export { default as Notice } from './Notice';
export { default as Search } from './Search';
export { default as Video } from './Video';
